<%@ Page Title="Compcare Wellness: Chronic Conditions Covered" Language="C#" MasterPageFile="~/TheScheme/SchemeNMP.master"
    AutoEventWireup="true" CodeBehind="ChronicConditionsCovered.aspx.cs" Inherits="CompCareWebsite.TheScheme.ChronicConditionsCovered" %>
<asp:Content ID="Content1" ContentPlaceHolderID="customScript" runat="server">
    <style type="text/css">
    </style>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="pageBody" runat="server">
    <h1>
        Chronic Conditions Covered</h1>
    <table align="right" cellpadding="0" cellspacing="0">
        <tr>
            <td>
                &nbsp;</td>
            <td style="width: 250px; text-align: right">
                
            </td>
            <td style="width:15px">&nbsp;</td>
            <td>
                <img src="../Images/pdfIcon.png" alt="Download pdf" />
            </td>
            <td style="width: 200px; text-align: right">
                <a href="../Downloads/ChronicConditionsCovered.pdf" target="_blank">Download
                    this content to pdf</a>
            </td>
        </tr>
    </table>
    <br />
    <br />
    <br />
    <p class="radialShadow">&nbsp;</p>
    <table cellspacing="0" align="center">
    <thead>
        <tr>
            <th class="on">
                Condition
            </th>
            <th>
                Pinnacle
            </th>
            <th>
                Dynamix
            </th>
            <th>
                Symmetry
            </th>
            <th>
                Axis
            </th>
            <th>
                Mumed
            </th>
            <th>
                NetworX
            </th>
        </tr>
    </thead>
    <tbody class="priceBody">
        <tr>
            <td class="on">
                Addison’s Disease *
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Allergic Rhinitis
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Angina*
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Ankylosing Spondylitis
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Anorexia Nervosa
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Asthma *
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Attention Deficit Disorder
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes</td>
            <td>
                &nbsp;
                Yes</td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Barrett’s Oesophagus
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Behcet's Disease
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Benign Prostatic Hyperplasia
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Bipolar Mood Disorder *
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Bronchiectasis *
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Bulimia Nervosa
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Cardiac Arrhythmias *
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Cardiomyopathy *
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Chronic Renal Failure *
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Congestive Cardiac Failure *
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Conn’s Syndrome
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Chronic Obstructive Pulmonary Disease *
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Emphysema*
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Chronic Bronchitis
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Connective Tissue Disorders (mixed)
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Coronary Artery Disease *
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Crohn’s Disease *
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Cushing’s Syndrome
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Cystic Fibrosis
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Deep Vein Thrombosis
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Diabetes Insipidus *
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Diabetes Mellitus Type 1 *
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Diabetes Mellitus Type 2*
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Epilepsy *
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Generalised Anxiety Disorder
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Glaucoma *
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Gastro-Oesophageal Reflux Disease
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Gout
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Haemophillia&nbsp;*
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Hiv/Aids *
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Huntington's Disease
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Hypercholesterolaemia/ Hyperlipidaemia *
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Hypertension *
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Hypoparathyroidism
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Hypothyroidism *
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Ischaemic Heart Disease*
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes &nbsp;
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Menopause/HRT*
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes &nbsp;
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Motor Neuron Disease
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Multiple Sclerosis *
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Muscular Dystrophy
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Myasthenia Gravis
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Narcolepsy
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Obsessive Compulsive Disorder
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Osteoarthritis
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Osteoporosis
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Paget’s Disease of the Bone
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Panic Disorder
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Paraplegia/ Quadriplegia
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Parkinson’s Disease*
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Pemphigus
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Peripheral Arterio-Sclerotic Disease
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Polyarteritis Nodosa
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Post-Traumatic Stress Syndrome
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Psoroasis/Psoriatic Arthritis
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Pulmonary Interstitial Fibrosis
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Rheumatoid Arthritis*
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Schizophrenia*
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Scleroderma (systemic sclerosis)
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Stroke
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Systemic Lupus Erythematosus*
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Thrombocytopaenic Purpura
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Ulcerative Colitis*
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
        </tr>
        <tr>
            <td class="on">
                Unipolar Mood Disorder/Major Depression
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Valvular Heart Disease
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                Zollinger-Ellison Syndrome
            </td>
            <td>
                Yes
            </td>
            <td>
                Yes
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td class="on">
                TOTAL CONDITIONS COVERED
            </td>
            <td>
                72
            </td>
            <td>
                62</td>
            <td>
                46
            </td>
            <td>
                27
            </td>
            <td>
                27
            </td>
            <td>
                27
            </td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <td class="on">
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
        </tr>
    </tfoot>
    </table>
</asp:Content>
