<%@ Page Title="Compcare Wellness: Contribution Comparison" Language="C#" MasterPageFile="~/TheScheme/SchemeNMP.master"
    AutoEventWireup="true" CodeBehind="ContributionComparison.aspx.cs" Inherits="CompCareWebsite.TheScheme.ContributionComparison" %>
<asp:Content ID="Content1" ContentPlaceHolderID="customScript" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="pageBody" runat="server">
    <table align="right" cellpadding="0" cellspacing="0">
        <tr>
            <td>
                <img src="../Images/pdfIcon.png" alt="Download pdf" />
            </td>
            <td style="width: 170px; text-align: right">
                <a href="../Downloads/AxisOption.pdf" target="_blank">Download this content to pdf</a>
            </td>
        </tr>
    </table>
    <br />
    <h1>Contribution Comparison</h1>
    <h2>Traditional Plans</h2>
    <table border="1" cellspacing="0">
        <tr>
            <td>
                &nbsp;
            </td>
            <td>
                Pinnacle
            </td>
            <td>
                Dynamix
            </td>
            <td>
                Symmetry
            </td>
            <td>
                Axis
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td>
                Savings
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td>
                Principal
            </td>
            <td>
                654
            </td>
            <td>
                492
            </td>
            <td>
                -
            </td>
            <td>
                -
            </td>
        </tr>
        <tr>
            <td>
                Adult
            </td>
            <td>
                510
            </td>
            <td>
                384
            </td>
            <td>
                -
            </td>
            <td>
                -
            </td>
        </tr>
        <tr>
            <td>
                Child
            </td>
            <td>
                180
            </td>
            <td>
                138
            </td>
            <td>
                -
            </td>
            <td>
                -
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td>
                Risk
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td>
                Principal
            </td>
            <td>
                2610
            </td>
            <td>
                1968
            </td>
            <td>
                -
            </td>
            <td>
                -
            </td>
        </tr>
        <tr>
            <td>
                Adult
            </td>
            <td>
                2034
            </td>
            <td>
                1536
            </td>
            <td>
                -
            </td>
            <td>
                -
            </td>
        </tr>
        <tr>
            <td>
                Child
            </td>
            <td>
                726
            </td>
            <td>
                552
            </td>
            <td>
                -
            </td>
            <td>
                -
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td>
                Total Contributions
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td>
                Principal
            </td>
            <td>
                3264
            </td>
            <td>
                2460
            </td>
            <td>
                1950
            </td>
            <td>
                1152
            </td>
        </tr>
        <tr>
            <td>
                Adult
            </td>
            <td>
                2544
            </td>
            <td>
                1920
            </td>
            <td>
                1518
            </td>
            <td>
                900
            </td>
        </tr>
        <tr>
            <td>
                Child
            </td>
            <td>
                906
            </td>
            <td>
                690
            </td>
            <td>
                552
            </td>
            <td>
                342
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td>
                Annual day-to-day benefits before threshold
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Principal
            </td>
            <td>
                9806
            </td>
            <td>
                5904
            </td>
            <td>
                -
            </td>
            <td>
                -
            </td>
        </tr>
        <tr>
            <td>
                Adult
            </td>
            <td>
                7646
            </td>
            <td>
                4608
            </td>
            <td>
                -
            </td>
            <td>
                -
            </td>
        </tr>
        <tr>
            <td>
                Child
            </td>
            <td>
                2704
            </td>
            <td>
                1656
            </td>
            <td>
                -
            </td>
            <td>
                -
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td>
                Annual SPG
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td>
                Principal
            </td>
            <td>
                1306
            </td>
            <td>
                2670
            </td>
            <td>
                -
            </td>
            <td>
                -
            </td>
        </tr>
        <tr>
            <td>
                Adult
            </td>
            <td>
                1018
            </td>
            <td>
                2082
            </td>
            <td>
                -
            </td>
            <td>
                -
            </td>
        </tr>
        <tr>
            <td>
                Child
            </td>
            <td>
                362
            </td>
            <td>
                744
            </td>
            <td>
                -
            </td>
            <td>
                -
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td>
                Threshold
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td>
                Principal
            </td>
            <td>
                11112
            </td>
            <td>
                8574
            </td>
            <td>
                -
            </td>
            <td>
                -
            </td>
        </tr>
        <tr>
            <td>
                Adult
            </td>
            <td>
                8664
            </td>
            <td>
                6690
            </td>
            <td>
                -
            </td>
            <td>
                -
            </td>
        </tr>
        <tr>
            <td>
                Child
            </td>
            <td>
                3066
            </td>
            <td>
                2400
            </td>
            <td>
                -
            </td>
            <td>
                -
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
    </table>
    <br />
    <h2>Salary Based Plans</h2>
    <table cellspacing="0" border="1">
        <tr>
            <td>
                &nbsp;
            </td>
            <td colspan="3">
                Mumed
            </td>
            <td colspan="5">
                Networx
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;
            </td>
            <td>
                13000+
            </td>
            <td>
                7901-13000
            </td>
            <td>
                0-7900
            </td>
            <td>
                7851+
            </td>
            <td>
                5251-7850
            </td>
            <td>
                3151-5250
            </td>
            <td>
                501-3150
            </td>
            <td>
                0-500
            </td>
        </tr>
        <tr>
            <td>
                Principal
            </td>
            <td>
                1674
            </td>
            <td>
                1398
            </td>
            <td>
                1278
            </td>
            <td>
                1434
            </td>
            <td>
                648
            </td>
            <td>
                492
            </td>
            <td>
                384
            </td>
            <td>
                306
            </td>
        </tr>
        <tr>
            <td>
                Adult
            </td>
            <td>
                1308
            </td>
            <td>
                1092
            </td>
            <td>
                996
            </td>
            <td>
                1434
            </td>
            <td>
                648
            </td>
            <td>
                492
            </td>
            <td>
                384
            </td>
            <td>
                306
            </td>
        </tr>
        <tr>
            <td>
                Child
            </td>
            <td>
                468
            </td>
            <td>
                396
            </td>
            <td>
                360
            </td>
            <td>
                516
            </td>
            <td>
                372
            </td>
            <td>
                294
            </td>
            <td>
                228
            </td>
            <td>
                168
            </td>
        </tr>
    </table>
</asp:Content>
